services:
  
  spark:
    image: docker.io/bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - ../scripts:/app/scripts
      - ../model:/app/model
      - ../checkpoints:/app/checkpoints

    mem_limit: 4g
    cpus: 2

    networks:
      - infrastructure_kafka-net

networks:
  infrastructure_kafka-net:
    external: true